#!/bin/bash

# Date
DATE=$(date "+%Y-%m-%d")

# Total Git Commits
COMMITS=$(git rev-list --count HEAD)

# Count .py lines excluding venv and .git
LOC=$(find . -type f \( -path "./week-01-foundation/project_merge/venv/*" -o -path "*/.git/*" \) -prune -o -name "*.py" -print | xargs wc -l | tail -n 1 | awk '{print $1}')

# Ask for user input: hours worked
echo -n "Enter hours worked today: "
read HOURS

# Append to CSV
echo "$DATE,$COMMITS,$LOC,$HOURS" >> progress_log.csv
echo "✅ Progress logged to progress_log.csv"

