## Find the difference LeetCode 389 Easy 

"""
Problem Statement:
You are given two strings s and t.

Strings t is generated by randomly shuffling strings s and then adding one extra characters at random position.

Return the extra character that was added to t.

some examples:
inputs:
s = "abcd"
t = "abcde"
output:
> "e" is the extra character

inputs:
s = "xyz"
t = "xzyq"
output:
s = "xyz"
t = "xzyq"
"""
from collections import Counter
def finding_extra(s, t):
    return (Counter(t) - Counter(s)).popitem()[0]


s = "abcd"
t = "abcde"            
print(finding_extra(s, t))
print(finding_extra("xyz", "xzyq"))

